- title: "NETWORK AND INFRASTRUCTURE VULNERABILITY ASSESSMENTS"
  description: "Focuses on both internal and perimeter critical devices such as firewalls, routers, servers, databases and appliances"
  icon: "ion-network"
- title: "WEB APPLICATION VULNERABILITY ASSESSMENTS"
  description: "In depth manual and automated tests against the application's design, logic, and underlying web server. (includes thin & thick client testing)"
  icon: "ion-android-laptop"
- title: "MOBILE SECURITY"
  description: "Impervious Solutions has created a thorough mobile testing methodology focusing on the following:
                <ul>
                <li>Application Design Review</li><li>Threat Modeling</li>
							  <li>Comprehensive Mobile Application Security Assessments</li>
							  <li>Code Review</li>
							  <li>Forensic Analysis</li>
                </ul>"
  icon: "ion-iphone"
- title: "DEEP SOURCE CODE REVIEW FOR WEB APPLICATIONS"
  description: "A comprehensive web application security analysis of developers source code. This is ideal for in house developed web applications."
  icon: "ion-code"
- title: "SBVA TESTING (STANDARD BUILD VULNERABILITY ASSESSMENTS)"
  description: "Security Assessments performed against Pre-production Devices or Applications. Commonly performed for custom desktop or server OS roll-outs, new product introduction or application major release updates. Example: once system engineers finish applying all application and security policies that will be included in what will be the production version, this final assessment will be performed to identify any remaining security issues prior to Production Roll Out. "
  icon: "ion-android-clipboard"
- title: "FULL COMPLIANCE AUDITING"
  description: "Certified testing available for: Sarbanes-Oxley (SOX), GLBA, PCI, HIPAA"
  icon: "ion-clipboard"
- title: "FIREWALL, ROUTER, & IDS/IPS CONFIGURATION, MAINTENANCE, MONITORING AND LOG ANALYSIS"
  description: ""
  icon: "ion-wrench"
- title: "WIRELESS ASSESSMENTS"
  description: "Including wireless architecture, access-point configuration (war-driving) and applied encryption technologies"
  icon: "ion-wifi"
- title: "SECURITY CONSULTING SERVICES"
  description: "Architecture Design reviews includes network device configuration and location reviews. Plus, Cloud computing and Hosting services"
  icon: "ion-android-lock"
- title: "INCIDENT HANDING/INCIDENT RESPONSE (POST INCIDENT HANDLING AND RECOVERY)"
  description: "Identify, Contain, Eradicate, and Recover from an attack"
  icon: "ion-android-warning"
- title: "FEATURES AND BENEFITS"
  description: "Impervious Solutions' proprietary assessment technology (IPSCAN) scans your environment faster and probes deeper while working with other leading products to extend your control:
              <ul>
              <li> Part of an Integrated Portfolio: Vulnerability Assessment Services are part of a fully integrated end-to-end security solution.</li>
              <li> End-to-end continuity of service and accountability.</li>
              <li> Proactive identification of vulnerabilities in your environment and integration with security response and remediation services enable increased control of risk.</li>
              <li> Part of a global service offering. Business-driven Approach Detailed analysis of business needs, drivers and the existing environment identifies the business critical areas.</li>
              <li>Ensures maximum protection for business-critical operations and provides the most cost-effective use of technology and resources. This enables clients to focus on core business functions.</li>
            </ul>"
  icon: "ion-qr-scanner"
- title: "INNOVATIVE TECHNOLOGY"
  description: "Impervious Solutions' proprietary assessment technology (IPSCAN) scans your environment faster and probes deeper while working with other leading products to extend your control
              <ul>
              <li>Recursive analysis minimizes false-positives to an as yet unforeseen level of accuracy.</li>
              <li>Asset-based scanning engine examines and identifies all network devices across the environment.</li>
              </ul>"
  icon: "ion-ios-cog"